Repository openai-php/client, pull requests merged in 2025-04, with the labels that each got.

#550 fix: correct completion endpoint when logprobs missing
  src/Responses/Completions/CreateResponseChoice.php
  tests/Responses/Completions/CreateResponseChoice.php
Labels: bug

#551 feat: support 'attributes' on vector store files
  src/Resources/VectorStoresFileBatches.php
  src/Resources/VectorStoresFiles.php
  src/Responses/VectorStores/Files/VectorStoreFileListResponse.php
  src/Responses/VectorStores/Files/VectorStoreFileResponse.php
  src/Testing/Responses/Fixtures/VectorStores/Files/VectorStoreFileListResponseFixture.php
  src/Testing/Responses/Fixtures/VectorStores/Files/VectorStoreFileResponseFixture.php
  src/Testing/Responses/Fixtures/VectorStores/VectorStoreListResponseFixture.php
  tests/Fixtures/VectorStoreFile.php
  tests/Responses/VectorStores/Files/VectorStoreFileResponse.php
Labels: enhancement

#502 feat: add OpenAI compatibility support for Google Gemini
  src/Responses/Chat/CreateResponse.php
  src/Responses/Chat/CreateStreamedResponse.php
  src/Responses/Embeddings/CreateResponse.php
  src/Responses/Embeddings/CreateResponseEmbedding.php
  tests/Fixtures/Chat.php
  tests/Fixtures/Embedding.php
  tests/Responses/Chat/CreateResponse.php
  tests/Responses/Chat/CreateStreamedResponse.php
  tests/Responses/Embeddings/CreateResponse.php
  tests/Responses/Embeddings/CreateResponseEmbedding.php
Labels: Non-OpenAI Model

#554 fix: chat completion choices to allow responses without logprobs field
  src/Responses/Chat/CreateResponseChoice.php
  tests/Fixtures/Chat.php
  tests/Responses/Chat/CreateResponseChoice.php
Labels: bug, Non-OpenAI Model

#530 Add compatibility for aliyun LLM APIs
  src/Responses/Files/CreateResponse.php
  src/Responses/Files/RetrieveResponse.php
  src/Responses/FineTunes/RetrieveResponseFile.php
  tests/Responses/Files/RetrieveResponse.php
Labels: Non-OpenAI Model
